# Generated by Django 4.2.6 on 2023-11-07 13:18

from django.db import migrations

def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(do_nothing),
    ]
